version: 2

sources:
  - name: staging
    database: chrome-encoder-375816
    schema: trips_data_all

    tables:
      - name: fhv_tripdata
      - name: green_tripdata
      - name: yellow_tripdata
